### ISSUE TITLE
MonkeyTrouble

### ISSUE THREAD

**Issue by anzeljg** [graded-cs-resources/CodingBatPseudo#1]
Hi.

I've tested MonkeyTrouble and since this is classic XOR I think this would be a more suitable solution:
```
method MonkeyTrouble(ASMILE, BSMILE)
  if ASMILE = BSMILE then
    output "TRUE"
  else
    output "FALSE"
  end if
end method
```

**Comment by DavidGriswoldTeacher** [comment]
I didn't go that route because as the very first warmup problem, I assume most working on it will be fairly novice programmers.

I'll add it as a comment in the solution, though.
